/* config.h.  Generated by configure.  */
/* config.h.in.  Generated automatically from configure.in by autoheader.  */

/* Define as the return type of signal handlers (int or void).  */
#define RETSIGTYPE void

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you can safely include both <sys/time.h> and <time.h>.  */
#define TIME_WITH_SYS_TIME 1

/* Define if lex declares yytext as a char * by default, not a char[].  */
#define YYTEXT_POINTER 1

/* Version of super-smack */
#define VERSION "1.1"

/* Define if we have a crypt() */
#define HAVE_CRYPT 1

/* MySQL Support */
#define HAVE_MYSQL 1

/* PostgreSQL Support */
#define HAVE_PGSQL 1

/* Oracle Support */
/* #undef HAVE_ORACLE */

/* Sample .smack data files */
#define SMACK_DATADIR "/var/smack-data"

/* Define if you have the gettimeofday function.  */
#define HAVE_GETTIMEOFDAY 1

/* Define if you have the strerror function.  */
#define HAVE_STRERROR 1

/* Define if you have the <sys/time.h> header file.  */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Define if you have the crypt library (-lcrypt).  */
#define HAVE_LIBCRYPT 1

/* Define if you have the z library (-lz).  */
#define HAVE_LIBZ 1

/* Name of package */
#define PACKAGE "super-smack"

/* Version number of package */
#define VERSION "1.1"

